### ISSUE TITLE
Add error types (mask) in Handler constructor

### ISSUE THREAD

**Issue by kslimani** [kslimani/cerberus#3]
By default, internal error handler registered by Cerberus is affected by the value of error_reporting() PHP function.
Adding an optional mask parameter in ErrorHandler constructor will allow Cerberus to register internal error handler using set_error_handler() with the mask as second parameter (if set in constructor).
Then error_reporting() settings will have no effect and internal error handler will be called regardless.

**Comment by kud** [comment]
When do you think it'll be available? I really need it for my own project.
